<script lang="ts">
	import * as p from '$lib/persisted.svelte';
	import { AsciiArt } from 'svelte-asciiart';
	import dbg from 'debug';
	const debug = dbg('app:AsciiRenderer');

	let { text, rows, cols, margin = 1, fontWeight = undefined, textStrokeWidth = undefined, ...rest } = $props();
</script>

<div
	class="w-full h-full overflow-hidden ascii-theme-{p.asciiStyle.current}"
	style="color: var(--ascii-fg); background: var(--ascii-bg); --ascii-text-stroke-width: {textStrokeWidth ?? '0'}; {fontWeight
		? `--ascii-font-weight: ${fontWeight};`
		: ''}">
	<AsciiArt {text} {rows} {cols} grid={false} {margin} frame={true} gridClass="ascii-grid" frameClass="ascii-frame" {...rest} />
</div>

<style>
	/* Target the SVG text elements generated by AsciiArt */
	div :global(svg text) {
		font-family: var(--ascii-font-family) !important;
		font-weight: var(--ascii-font-weight) !important;
		stroke: currentColor;
		stroke-width: var(--ascii-text-stroke-width);
		paint-order: stroke fill;
	}
</style>
